language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t santosh0150/docker-react -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true santosh0150/docker-react npm run test

after_success:
 - docker build -t santosh0150/multi-client ./client
 - docker build -t santosh0150/multi-ngnix ./ngnix
 - docker build -t santosh0150/multi-server ./server
 - docker build -t santosh0150/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push santosh0150/multi-client
 - docker push santosh0150/multi-ngnix
 - docker push santosh0150/multi-server
 - docker push santosh0150/multi-worker

